<?php
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Link;


/**
 * Implements hook_base_form_alter().
 *
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function as_showcase_theme($existing, $type, $theme, $path){
    return array(
        'showcase_parallax' => [
        'variables' => [
            'results' => NULL,            
        ]
    ]);
}
function as_showcase_form_alter(&$form, $form_state, $form_id) {
    $alterformid=$form['#id'];
}
